[power_attack]
text = ["""
Trades attack bonus for damage at a very good rate, extremely good if the weapon is \
held in two hands. The main source of damage scaling for almost all melee builds in pathfinder.
"""]

[two-weapon_fighting_line]
text = ["""
These feats are so tied to the fighting style that there's really not much point in having \
a different article.
"""]
subfeats = ["two-weapon_fighting", "improved_two-weapon_fighting", "greater_two-weapon_fighting"]

[mobile_bulwark_line]
subfeats = ["mobile_bulwark_style", "mobile_fortress", "mobile_stronghold"]
text = ["""
The first feat lets you become totally immune to non-spell attacks from one direction as a move action. \
Probably mainly of interest to casters, who can be at range (where this ability shines) and who often have a move action spare \
but also usable by mounted characters, who have a move action free after a mounted charge. """,
"""
The second feat represents a dramatic increase to Touch AC, which is of interest to anyone, and extends your \
directional protection to allies (including potentially your mount). 
""",
"""
The third feat lets you negate an attack as an immediate action, which is extremely powerful. Not much more to say.
""",
"""
These feats all also gradually reduce the penalties associated with using a weapon alongside a tower shield, which is nice. \
"""]

[mobile_bulwark_style]
article_redirect = "mobile_bulwark_line"

[mobile_fortress]
article_redirect = "mobile_bulwark_line"

[mobile_stronghold]
article_redirect = "mobile_bulwark_line"

[two-weapon_fighting]
article_redirect = "two-weapon_fighting_line"

[improved_two-weapon_fighting]
article_redirect = "two-weapon_fighting_line"

[improved_two-weapon_fighting.prereqs]
feats = ["two-weapon_fighting"]

[greater_two-weapon_fighting]
article_redirect = "two-weapon_fighting_line"

[greater_two-weapon_fighting.prereqs]
feats = ["two-weapon_fighting", "improved_two-weapon_fighting"]

[weapon_finesse]
text = ["""
Allows you to use your Dex bonus to determine accuracy (not damage) with certain melee weapons - all light \
 weapons and some special one-and-two-handed weapons. 
"""]

[starry_grace]
text = ["""
Gives you Dex to damage with starknives, including when throwing them - which basically makes them the best \
thrown weapon. Requires an empty off-hand and incompatible with Flurry of Blows and things that work like Two-Weapon Fighting. \
Doesn't forbid shields, and an arm with a buckler strapped on counts as free, so you have no reason not to use one. 
""",
"""
Also gives a move-speed bonus after attacking that'll be quite useful before full attacking becomes mandatory"""]

[starry_grace.prereqs] 
feats = ["weapon_focus", "weapon_finesse"]

[fencing_grace]
text = ["""
Gives you Dex to damage with the rapier, and a minor bonus against disarm. Requires an empty off-hand \
and incompatible with special combat actions like Flurry of Blows. Doesn't forbid shields, and an arm \
with a buckler strapped on counts as free, so you have no reason not to use one. 
""",
"""Note that rapiers cannot be used with piranha style without a \ 
specific magic item (effortless lace), so at higher levels they actually have worse damage than a light \
slashing weapon used with Slashing Grace.
"""]

[fencing_grace.prereqs]
feats = ["weapon_focus", "weapon_finesse"]

[piranha_strike]
text = ["""
Power attack, but for light weapons - makes you a bit more inaccurate and a lot more damaging. Given that \
this is light weapons only, this means that Dex melee characters might want to stay away from special finessable \ 
weapons like rapiers, as they don't qualify for this. An item does exist to get around this, Effortless Lace - \
whether dependence on a specific item like that is acceptable is for you to decide.
"""]

[piranha_strike.prereqs]
feats = ["weapon_finesse"]

[slashing_grace]
text = ["""
Gives you Dex to damage with any slashing weapon. Requires an empty off-hand and incompatible with Flurry of Blows. \
And things that work with two-weapon fighting Doesn't forbid shields, and an arm with a buckler strapped on counts as 
free, so you have no reason not to use one.
"""]

[slashing_grace.prereqs]
feats = ["weapon_focus", "weapon_finesse"]

[rapid_shot]
text = ["""
Gives you an additional attack for a very low penalty. """,
"""
Not much to say, this is just really good. Take it, use it every round.
"""]

[rapid_shot.prereqs]
feats = ["point_blank_shot"]

[precise_shot]
text = ["""
Without this feat, firing into melee (which you will be doing most of the time) has an extremely large penalty. \
Basically mandatory for ranged characters, even potentially wanted on ray specialist mages.
"""]

[precise_shot.prereqs]
feats = ["point_blank_shot"]


[dervish_dance]
text = ["""
Dex-to-damage with the scimitar. Fewer prereqs than most sources of Dex-to-damage. Generally works similarly to \
the others, except it forbids shields entirely (no bucklers) as well as off-hand weapons. Allows the other hand to \
be used in other ways, though - works with flurry, spell combat, etc.
"""]

[dervish_dance.prereqs]
feats = ["weapon_finesse"]

[difficult_swings]
text = ["""
When you take a full attack, squares near you become difficult terrain. Difficult terrain is harder to move into, not \
out of, so this doesn't stop people from escaping like you might think. However, if you have access to reach (from a reach \
weapon or Lunge) it greatly inconveniences medium melee enemies, as they cannot 5-foot step in to full attack you after \
you full attack them. 
"""]

[difficult_swings.prereqs]
feats = ["martial_focus"]

[spirit_focus_-_champion]
text = ["""
Gives +1 to attack, damage, and Fort saves. That's equal to the benefits from Weapon Focus, half a Weapon Specialisation, \
and half a Great Fortitude. Optimistically, that means this feat is worth two feats. All the feats above are bad, though, \
being worth probably about half a feat each - but still, that suggests this feat is a decently valuable package.
"""]

[steadfast_personality]
text = ["""
Add your Cha bonus instead of your Wis bonus to mind-affecting Will saves (which is almost all Will saves). If you have a Wis \
penalty, you still take it, so you can't entirely dump it. If your Cha mod is at least +4 higher than your Wis mod this is \
probably good enough to be worth picking up. A bad Will save is a really unfortunate weakness - fail a save against a
<em>dominate</em> at the wrong time and everyone's dead.
"""]

[noble_scion_-_war]
text = ["""
Gives you a bonus to initiative equal to your Charisma. If your main stat is Cha, this will be a better Improved Initiative, \
and that's a good thing indeed. Classes with Cha as a secondary stat will likely get to that point eventually through headbands. \
"""]

[eldritch_heritage_-_arcane]
text = ["""
If you have the Cha, this is two feats to get a full familiar (which takes 3 feats the normal way). This opens up familiar archetypes, \
which are quite exciting.<br>
Some applications include:
<ul>
<li>Guardian familiars act as hp batteries - for two feats, you effectively multiply your health by 1.5x.</li>
<li>Mauler familiars inherit your BAB and a fraction of your health - they're actually decent combatants</li>
<li>Valet familiars gain your teamwork feats, which is potentially very useful with Coordinated Charge. They also help you craft, if you're into that.</li>
<li>Sages have their own knowledge ranks, and eventually scale up to be better at knowledge checks than most PCs</li>
<li>As a full familiar, arcane heritage familiars qualify for Improved Familiar</li>
</ul>
"""]

[dirty_fighting]
text = ["""
The base ability of this feat is just okay. While flanking, you get better at combat maneuvers you have invested in, and dodge \
some of the penalties for those you haven't. The real draw, however, is that this feats sidesteps the often-terrible prerequisites \
for the various "Improved Combat Maneuver" feats.
"""]

[dazing_assault]
text = ["""
This feat requires BAB+11. People generally stop playing around level 12-13. That makes this basically the capstone for full-BAB \
melee characters with the strength to take it. And it's a good one. At the cost of an admittedly quite high penalty to accuracy, \
you force enemies to make a Fort save or lose their next turn every time you hit them. The DC is quite high, and in general the \
best way to force enemies to fail a save is to force them to make multiple, so this is quite often able to just lock enemies down \
until they die. 
""",
"""
The main downside is that the save is Fortitude, which tends to be the highest monster save, and which means that undead and constructs \
are immune to this ability. In some campaigns, this makes this quite bad. 
"""
]

[dazing_assault.prereqs]
feats = ["power_attack"]

[possessed_hand_line]
text = ["""
This line of feats is funky and surprisingly useful. You invite a spirit of some sort into your hand, and it gives you increasing \
benefits as you gain levels.
""",
"""
The first feat is mildly underwhelming - +1 to some skills and to attack and damage for weapons held in the hand. The once/day swift \
action retrieve is nice, but ultimately just a more versatile Spring-Loaded Wrist Sheath.
""",
"""
The second feat, however, is quite exciting. Firstly, it reduces the penalties for Two-Weapon Fighting by enough to dual-wield one-handed \
instead of light weapons, if you happen to like the visuals of using two swords. Also, when you're downed or incapacitated, your hand can \
act autonomously. Given how prominent control effects are in pathfinder, any defence against them is amazingly useful. Just carry some \
potions of Surmount Affliction, and your hand can feed them to you, capping the duration of such effects against you at one round.
""",
"""
The final feat allows the hand to detatch and act on its own as a familiar. You don't get the full familiar abilities, which is sad, but \
if you already have a familiar you can choose for it to be the hand, allowing it to take familiar archetypes. Notably, the hand is diminutive \
but has quite good Str - if you take Mauler, then when your hand grows to medium in battle form its Str becomes a respectable base 19 before \
applying the Mauler increases. For the feat investment, this isn't broken or anything, but it's kind of amazing that you can do it.
"""
]

subfeats = ["possessed_hand", "hand's_autonomy", "hand's_detatchment"]

[possessed_hand]
article_redirect = "possessed_hand_line"

["hand's_autonomy"]
article_redirect = "possessed_hand_line"

["hand's_autonomy".prereqs]
feats = ["possessed_hand"]

["hand's_detatchment"]
article_redirect = "possessed_hand_line"

["hand's_detatchment".prereqs]
feats = ["possessed_hand", "hand's_autonomy"]

[combat_reflexes]
text = ["""
Gives you extra AoOs each round equal to your Dex mod. This feat isn't strictly necessary to make using a reach weapon worth \
it, but it really is pretty amazing. It's one of the most effecive ways for non-casters to deal with crowds, it lets you AoO \
people before you've acted to make sure you always get that free attack off, and it prevents you from ever needing to make \
a choice about whether to take that AoO or leave it open to keep threatening that caster or whatever. You don't need much Dex for \
this to be worth it, 14 or so is enough - being a Dex build and getting 10 a cap of AoOs a round is fun, but you'll rarely ever \
get to use that many.""",

"""Of note is the fact that Dex is probably the most annoying attribute this could scale off of - this feat makes you want reach \
which means you want to get big, but getting big reduces your Dex."""]

[improved_trip_line]
text = ["""
The first feat here is the same as all the other Improved X feats - +2 to CMB, and you don't provoke when you try. If you \ 
get hit on the AoO from a combat maneuver, you take the damage as a penalty to your CMB, so without a way to avoid this \
combat maneuvers are generally not even worth trying.  
""",
"""
Greater trip is simple but delicious - when you trip someone, you get to attack them. As long as you succeed, trying to trip \
doesn't even cost you the damage the attack it replaced would have dealt.
""",
"""
The nice thing about trip is: here it stops. Other combat maneuvers have further feats you really want to improve their action \
economy, but trip has all that baked in. 
"""]

subfeats = ["improved_trip", "greater_trip"]

[improved_trip]
article_redirect = "improved_trip_line"

[improved_trip.prereqs]
feats = [["", "dirty_fighting", "combat_expertise"]]

[greater_trip]
article_redirect = "improved_trip_line"

[greater_trip.prereqs]
feats = [["", "dirty_fighting", "combat_expertise"], "improved_trip"]
